DROP DATABASE IF EXISTS `sys`;
CREATE DATABASE `sys` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `sys_job`;
CREATE DATABASE `sys_job` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `sys_register`;
CREATE DATABASE `sys_register` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `sys_seata`;
CREATE DATABASE `sys_seata` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `sys_pay`;
CREATE DATABASE `sys_pay` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `sys_generator`;
CREATE DATABASE `sys_generator` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;



