DROP DATABASE IF EXISTS `xhuicloud_sys`;
CREATE DATABASE `xhuicloud_sys` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `xhuicloud_seata`;
CREATE DATABASE `xhuicloud_seata` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `xhuicloud-register`;
CREATE DATABASE `xhuicloud-register` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `xhuicloud_pay`;
CREATE DATABASE `xhuicloud_pay` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `xhuicloud_job`;
CREATE DATABASE `xhuicloud_job` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

DROP DATABASE IF EXISTS `xhuicloud_gen`;
CREATE DATABASE `xhuicloud_gen` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;



